# Generated by Django 4.1.6 on 2023-02-16 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=100)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('obyektivka', models.FileField(blank=True, null=True, upload_to='files/obyektivka', validators=[main.models.validate_file_size, main.models.validate_file_extension])),
                ('turdavoy', models.FileField(blank=True, null=True, upload_to='files/turdavoy', validators=[main.models.validate_file_size, main.models.validate_file_extension])),
                ('staj', models.IntegerField(default=0)),
                ('lavozim', models.CharField(max_length=200)),
                ('passport', models.CharField(max_length=10)),
                ('id_filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_filial', to='main.filial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
